---
# ansible_role_sep/tasks/redhat_uninstall.yml
# Author: MTO 
# Description: Tasks for un-installing Symantec Endpoint Protection client for Redhat.
# 
- name: SEP - Uninstall - Execute script install.sh to uninstall (RedHat)
  command: sh -c "{{ sep_rh_dir_install }}/install.sh -u"
  register: sep_install_output
  ignore_errors: yes

- name: SEP - Uninstall - Execute script install.sh to uninstall (Redhat)
  debug: msg="{{ sep_install_output.stdout_lines }}"