---
# ansible_role_sep/tasks/redhat_uninstall.yml
# Author: MTO 
# Description: Tasks for un-installing Symantec Endpoint Protection client for Redhat.
# 
- name: SEP - Redhat - Execute script install.sh to uninstall
  command: sh -c "{{ sep_rh_dir_install }}/install.sh -u"