---
# ansible_role_sep/tasks/redhat_install.yml
# Author: MTO 
# Description: Tasks for installing Symantec Endpoint Protection client for Redhat.
# 
- name: SEP - Redhat - Create directory {{ sep_rh_dir_install }}
  file:
    path: "{{ sep_rh_dir_install }}"
    state: directory
    owner: root
    group: root
    mode: '755' 

- name: SEP - Redhat - Install unzip
  package:
    name:
      - unzip
    state: latest

- name: SEP - Redhat - Download and unarchive {{ sep_rh_file_install }}
  unarchive:
    src: "{{ sep_rh_repo }}/{{ sep_rh_file_install }}"
    dest: "{{ sep_rh_dir_install }}"
    remote_src: yes

- name: SEP - Redhat - Set the execute file permissions on install.sh
  file:
    path: "{{ sep_rh_dir_install }}/install.sh"
    owner: root
    group: root
    mode: '755'   

- name: SEP - Redhat - Execute script install.sh
  command: sh "{{ sep_rh_dir_install }}/install.sh -i"